### PR TITLE
Add var/report folder to shared directories

### PR DESCRIPTION
**Pull request by BorisovskiP**

### CODE REVIEW

**Comment by osrecio** [comment]
You have the availabity to override the shared folders in your `deploy.php` 

in this way:

```
# File: deploy.php
set('shared_dirs', [
    '{{magento_dir}}/pub/media',
    '{{magento_dir}}/var/log',
    '{{magento_dir}}/var/backups',
    '{{magento_dir}}/var/session',
    '{{magento_dir}}/var/report',
]);
```

**Comment by sprankhub** [comment]
Of course you can do that, but why do we share the `var/log`log folder by default? Because it contains important information, which should be available independent of deployments. The `var/report` folder is exactly the same IMHO. It should be preserved by default.

**Comment by osrecio** [comment]
Sorry was my fault! 

I think all of var folder should be shared.

What do you think @sprankhub 

For example the file: .maintenance.flag should be included too, and the other ones.

**Comment by sprankhub** [comment]
The disadvantage of sharing the whole directory is, that the default file `var/.htaccess` is not under version control anymore. However, we currently also share the whole `media` directory and it probably makes sense. So yes, I would agree it makes sense although this is kind of a breaking change.

**Comment by sprankhub** [comment]
What do you think @osrecio? Should we merge this and create a ticket to discuss whether the whole `var` directory should be shared in the future?

**Comment by sprankhub** [comment]
@osrecio any chance that we merge this and discuss the inclusion of the whole `var` directory in a separate issue?

**Comment by osrecio** [comment]
Hi @sprankhub @BorisovskiP I'm working to merge it.

Sorry I was in vacation last week :)

**Comment by osrecio** [comment]
New version [2.8.0](https://github.com/jalogut/magento2-deployer-plus/releases/tag/2.8.0)

Thanks @BorisovskiP :) and @sprankhub to push it

**Comment by sprankhub** [comment]
Thank **you**!

**Comment by BorisovskiP** [comment]
Thanks @osrecio !

**Pull request merged**
