### PR TITLE
Use deployers bin/php to execute magento_bin

### LINKED ISSUE #2: {{magento_bin}} ignores deployers {{bin/php}} setting
Hi,

I was playing around with this project and ran into some errors on build machines with multiple versions of php installed. 

TL;DR: {{magento_bin}} ignores deployers {{bin/php}} setting and executes the wrong php binary

The {{magento_bin}} command just executes the <root>/bin/magneot command, which in turn uses the env command in the shebang to determine which php executable to use 
(#!/usr/bin/env php)

In deployer it is possible to set another php executable with set('bin/php', ...) like this:
```php
set('bin/php', function () {
    return locateBinaryPath('php7.1');
});
```

The easiest fix would be to use "{{bin/php}}" to execute bin/magento.

To do this, in file recipe/magento_2_1.php change Line 27:

From:
```php
set('magento_bin', '{{bin/php}} {{magento_dir}}/bin/magento');
```
To:
```php
set('magento_bin', '{{magento_dir}}/bin/magento');
```

### PR DESCRIPTION
**Pull request by renttek**
This PR fixes #2 and enables this deployer extension to work on build machines with different versions of php installed

### CODE REVIEW

**Comment by jalogut** [comment]
Hi @renttek 

Thanks for the contribution, I did not think about that.
We cannot merge the PR just yet because the `{{magento_bin}}` is used in other places as subpath. See for example:

* https://github.com/jalogut/magento2-deployer-plus/blob/bcb3af6ce193ee22c442306cfef116c5e81c762d/recipe/magento_2_1/maintenance.php#L14

 I think the best will be to add `bin/php` right behind every command execution. We could also change the name of `{{magento_bin}}` to `{{magento_bin_dir}}`.

What do you think?

**Comment by renttek** [comment]
Thats sounds good! I'll update the PR later when I get home :+1:

**Comment by renttek** [comment]
Hi @jalogut 

I updated the PR so that the bin/magento calls are prefix.

Im not quite sure about renaming `magento_bin` to `magento_bin_dir`. Peronally I think that there is a nice distinction between directories/variables (`my_file_path`) and commans (`bin/myCommand`).
Also no other file variable seems to have a `_dir` suffix, only directories.

**Comment by renttek** [comment]
Oh and I also put the vendor directory into the .gitignore

**Comment by jalogut** [comment]
@renttek great! Many thanks

**Pull request merged**
