### PR TITLE
Add {{magento_dir}}/pub/static/_cache to shared/writable/clear_paths

### PR DESCRIPTION
**Pull request by osrecio**
Add path /pub/static/_cache to Shared, Writable and Clear Paths.

When you have a multi-stage server and merged css or js this folder and subfolders are created to distribute css & js and you need to have it shared.

Added to clear paths because in each deploy we clean old files that will no longer be used.

### CODE REVIEW

**Comment by osrecio** [comment]
Actually the problem is:
Server 1 -> This server receives a request and create the js and css cache and url will change to: `store.com/pub/static/_cache/merged/1df1a823136ce6816cefe2f78dcdb61a.min.js`
Server 2 -> The file: `/pub/static/_cache/merged/1df1a823136ce6816cefe2f78dcdb61a.min.js` doesn't exist. Therefore it will not find it unless the folder is shared
Server 3 -> The file: `/pub/static/_cache/merged/1df1a823136ce6816cefe2f78dcdb61a.min.js` doesn't exist. Therefore it will not find it unless the folder is shared.

> each server will create their own, right?
Nope, the first server that recieve the request will create these files.

> So the _cache is only created once and then available for all others?
Is correct, the folder `merged` inside of `_cache` is actually the problem. You should share, but can be a good change to share `_cache`.

I hope it's clear now.

**Comment by jalogut** [comment]
Ok fair enough! Thanks

**Comment by jalogut** [comment]
@osrecio It seems that there are conflicts. I cannot do anything until tuesday, so feel free to fix them and create a new tag. I just added you as collaborator

**Comment by osrecio** [comment]
I will resolve conflicts tomorrow.
Thanks for give me a new role 😄

**Pull request merged**
